/* 
 * Klootzakken API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IGameApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Retrieve the state of a game
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <returns>GameView</returns>
        GameView GameByGameIdGet (string gameId);

        /// <summary>
        /// Retrieve the state of a game
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <returns>ApiResponse of GameView</returns>
        ApiResponse<GameView> GameByGameIdGetWithHttpInfo (string gameId);
        /// <summary>
        /// Play on of your possible actions in the game
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <param name="play">The details of your action - must be one of the possiblePlays from the game state (optional)</param>
        /// <returns>GameView</returns>
        GameView GameByGameIdPlayPost (string gameId, PlayView play = null);

        /// <summary>
        /// Play on of your possible actions in the game
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <param name="play">The details of your action - must be one of the possiblePlays from the game state (optional)</param>
        /// <returns>ApiResponse of GameView</returns>
        ApiResponse<GameView> GameByGameIdPlayPostWithHttpInfo (string gameId, PlayView play = null);
        /// <summary>
        /// Get all your and public lobbies
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;LobbyView&gt;</returns>
        List<LobbyView> LobbiesGet ();

        /// <summary>
        /// Get all your and public lobbies
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;LobbyView&gt;</returns>
        ApiResponse<List<LobbyView>> LobbiesGetWithHttpInfo ();
        /// <summary>
        /// Get the state of a particular lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId"></param>
        /// <returns>LobbyView</returns>
        LobbyView LobbyByLobbyIdGet (string lobbyId);

        /// <summary>
        /// Get the state of a particular lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId"></param>
        /// <returns>ApiResponse of LobbyView</returns>
        ApiResponse<LobbyView> LobbyByLobbyIdGetWithHttpInfo (string lobbyId);
        /// <summary>
        /// Join a Lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby to join</param>
        /// <returns>LobbyView</returns>
        LobbyView LobbyByLobbyIdJoinPost (string lobbyId);

        /// <summary>
        /// Join a Lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby to join</param>
        /// <returns>ApiResponse of LobbyView</returns>
        ApiResponse<LobbyView> LobbyByLobbyIdJoinPostWithHttpInfo (string lobbyId);
        /// <summary>
        /// Start the game for a lobby. The lobby will be converted to a game.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby</param>
        /// <returns>GameView</returns>
        GameView LobbyByLobbyIdStartPost (string lobbyId);

        /// <summary>
        /// Start the game for a lobby. The lobby will be converted to a game.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby</param>
        /// <returns>ApiResponse of GameView</returns>
        ApiResponse<GameView> LobbyByLobbyIdStartPostWithHttpInfo (string lobbyId);
        /// <summary>
        /// Create a new lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The name of the future game</param>
        /// <param name="isPublic">Indicates whether the lobby is visible to everyone (optional)</param>
        /// <returns>LobbyView</returns>
        LobbyView LobbyCreateByNamePost (string name, bool? isPublic = null);

        /// <summary>
        /// Create a new lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The name of the future game</param>
        /// <param name="isPublic">Indicates whether the lobby is visible to everyone (optional)</param>
        /// <returns>ApiResponse of LobbyView</returns>
        ApiResponse<LobbyView> LobbyCreateByNamePostWithHttpInfo (string name, bool? isPublic = null);
        /// <summary>
        /// Return the games you participate in
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;GameView&gt;</returns>
        List<GameView> MyGamesGet ();

        /// <summary>
        /// Return the games you participate in
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;GameView&gt;</returns>
        ApiResponse<List<GameView>> MyGamesGetWithHttpInfo ();
        /// <summary>
        /// Return the lobbies you&#39;ve created or joined
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;LobbyView&gt;</returns>
        List<LobbyView> MyLobbiesGet ();

        /// <summary>
        /// Return the lobbies you&#39;ve created or joined
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;LobbyView&gt;</returns>
        ApiResponse<List<LobbyView>> MyLobbiesGetWithHttpInfo ();
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Retrieve the state of a game
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <returns>Task of GameView</returns>
        System.Threading.Tasks.Task<GameView> GameByGameIdGetAsync (string gameId);

        /// <summary>
        /// Retrieve the state of a game
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <returns>Task of ApiResponse (GameView)</returns>
        System.Threading.Tasks.Task<ApiResponse<GameView>> GameByGameIdGetAsyncWithHttpInfo (string gameId);
        /// <summary>
        /// Play on of your possible actions in the game
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <param name="play">The details of your action - must be one of the possiblePlays from the game state (optional)</param>
        /// <returns>Task of GameView</returns>
        System.Threading.Tasks.Task<GameView> GameByGameIdPlayPostAsync (string gameId, PlayView play = null);

        /// <summary>
        /// Play on of your possible actions in the game
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <param name="play">The details of your action - must be one of the possiblePlays from the game state (optional)</param>
        /// <returns>Task of ApiResponse (GameView)</returns>
        System.Threading.Tasks.Task<ApiResponse<GameView>> GameByGameIdPlayPostAsyncWithHttpInfo (string gameId, PlayView play = null);
        /// <summary>
        /// Get all your and public lobbies
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;LobbyView&gt;</returns>
        System.Threading.Tasks.Task<List<LobbyView>> LobbiesGetAsync ();

        /// <summary>
        /// Get all your and public lobbies
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;LobbyView&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<LobbyView>>> LobbiesGetAsyncWithHttpInfo ();
        /// <summary>
        /// Get the state of a particular lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId"></param>
        /// <returns>Task of LobbyView</returns>
        System.Threading.Tasks.Task<LobbyView> LobbyByLobbyIdGetAsync (string lobbyId);

        /// <summary>
        /// Get the state of a particular lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId"></param>
        /// <returns>Task of ApiResponse (LobbyView)</returns>
        System.Threading.Tasks.Task<ApiResponse<LobbyView>> LobbyByLobbyIdGetAsyncWithHttpInfo (string lobbyId);
        /// <summary>
        /// Join a Lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby to join</param>
        /// <returns>Task of LobbyView</returns>
        System.Threading.Tasks.Task<LobbyView> LobbyByLobbyIdJoinPostAsync (string lobbyId);

        /// <summary>
        /// Join a Lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby to join</param>
        /// <returns>Task of ApiResponse (LobbyView)</returns>
        System.Threading.Tasks.Task<ApiResponse<LobbyView>> LobbyByLobbyIdJoinPostAsyncWithHttpInfo (string lobbyId);
        /// <summary>
        /// Start the game for a lobby. The lobby will be converted to a game.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby</param>
        /// <returns>Task of GameView</returns>
        System.Threading.Tasks.Task<GameView> LobbyByLobbyIdStartPostAsync (string lobbyId);

        /// <summary>
        /// Start the game for a lobby. The lobby will be converted to a game.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby</param>
        /// <returns>Task of ApiResponse (GameView)</returns>
        System.Threading.Tasks.Task<ApiResponse<GameView>> LobbyByLobbyIdStartPostAsyncWithHttpInfo (string lobbyId);
        /// <summary>
        /// Create a new lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The name of the future game</param>
        /// <param name="isPublic">Indicates whether the lobby is visible to everyone (optional)</param>
        /// <returns>Task of LobbyView</returns>
        System.Threading.Tasks.Task<LobbyView> LobbyCreateByNamePostAsync (string name, bool? isPublic = null);

        /// <summary>
        /// Create a new lobby
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The name of the future game</param>
        /// <param name="isPublic">Indicates whether the lobby is visible to everyone (optional)</param>
        /// <returns>Task of ApiResponse (LobbyView)</returns>
        System.Threading.Tasks.Task<ApiResponse<LobbyView>> LobbyCreateByNamePostAsyncWithHttpInfo (string name, bool? isPublic = null);
        /// <summary>
        /// Return the games you participate in
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;GameView&gt;</returns>
        System.Threading.Tasks.Task<List<GameView>> MyGamesGetAsync ();

        /// <summary>
        /// Return the games you participate in
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;GameView&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<GameView>>> MyGamesGetAsyncWithHttpInfo ();
        /// <summary>
        /// Return the lobbies you&#39;ve created or joined
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;LobbyView&gt;</returns>
        System.Threading.Tasks.Task<List<LobbyView>> MyLobbiesGetAsync ();

        /// <summary>
        /// Return the lobbies you&#39;ve created or joined
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;LobbyView&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<LobbyView>>> MyLobbiesGetAsyncWithHttpInfo ();
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class GameApi : IGameApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="GameApi"/> class.
        /// </summary>
        /// <returns></returns>
        public GameApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="GameApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public GameApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Retrieve the state of a game 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <returns>GameView</returns>
        public GameView GameByGameIdGet (string gameId)
        {
             ApiResponse<GameView> localVarResponse = GameByGameIdGetWithHttpInfo(gameId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Retrieve the state of a game 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <returns>ApiResponse of GameView</returns>
        public ApiResponse< GameView > GameByGameIdGetWithHttpInfo (string gameId)
        {
            // verify the required parameter 'gameId' is set
            if (gameId == null)
                throw new ApiException(400, "Missing required parameter 'gameId' when calling GameApi->GameByGameIdGet");

            var localVarPath = "/game/{gameId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (gameId != null) localVarPathParams.Add("gameId", Configuration.ApiClient.ParameterToString(gameId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GameByGameIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GameView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GameView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GameView)));
            
        }

        /// <summary>
        /// Retrieve the state of a game 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <returns>Task of GameView</returns>
        public async System.Threading.Tasks.Task<GameView> GameByGameIdGetAsync (string gameId)
        {
             ApiResponse<GameView> localVarResponse = await GameByGameIdGetAsyncWithHttpInfo(gameId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Retrieve the state of a game 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <returns>Task of ApiResponse (GameView)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GameView>> GameByGameIdGetAsyncWithHttpInfo (string gameId)
        {
            // verify the required parameter 'gameId' is set
            if (gameId == null)
                throw new ApiException(400, "Missing required parameter 'gameId' when calling GameApi->GameByGameIdGet");

            var localVarPath = "/game/{gameId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (gameId != null) localVarPathParams.Add("gameId", Configuration.ApiClient.ParameterToString(gameId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GameByGameIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GameView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GameView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GameView)));
            
        }

        /// <summary>
        /// Play on of your possible actions in the game 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <param name="play">The details of your action - must be one of the possiblePlays from the game state (optional)</param>
        /// <returns>GameView</returns>
        public GameView GameByGameIdPlayPost (string gameId, PlayView play = null)
        {
             ApiResponse<GameView> localVarResponse = GameByGameIdPlayPostWithHttpInfo(gameId, play);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Play on of your possible actions in the game 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <param name="play">The details of your action - must be one of the possiblePlays from the game state (optional)</param>
        /// <returns>ApiResponse of GameView</returns>
        public ApiResponse< GameView > GameByGameIdPlayPostWithHttpInfo (string gameId, PlayView play = null)
        {
            // verify the required parameter 'gameId' is set
            if (gameId == null)
                throw new ApiException(400, "Missing required parameter 'gameId' when calling GameApi->GameByGameIdPlayPost");

            var localVarPath = "/game/{gameId}/play";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/json-patch+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (gameId != null) localVarPathParams.Add("gameId", Configuration.ApiClient.ParameterToString(gameId)); // path parameter
            if (play != null && play.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(play); // http body (model) parameter
            }
            else
            {
                localVarPostBody = play; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GameByGameIdPlayPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GameView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GameView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GameView)));
            
        }

        /// <summary>
        /// Play on of your possible actions in the game 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <param name="play">The details of your action - must be one of the possiblePlays from the game state (optional)</param>
        /// <returns>Task of GameView</returns>
        public async System.Threading.Tasks.Task<GameView> GameByGameIdPlayPostAsync (string gameId, PlayView play = null)
        {
             ApiResponse<GameView> localVarResponse = await GameByGameIdPlayPostAsyncWithHttpInfo(gameId, play);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Play on of your possible actions in the game 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="gameId">Id of the game</param>
        /// <param name="play">The details of your action - must be one of the possiblePlays from the game state (optional)</param>
        /// <returns>Task of ApiResponse (GameView)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GameView>> GameByGameIdPlayPostAsyncWithHttpInfo (string gameId, PlayView play = null)
        {
            // verify the required parameter 'gameId' is set
            if (gameId == null)
                throw new ApiException(400, "Missing required parameter 'gameId' when calling GameApi->GameByGameIdPlayPost");

            var localVarPath = "/game/{gameId}/play";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/json-patch+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (gameId != null) localVarPathParams.Add("gameId", Configuration.ApiClient.ParameterToString(gameId)); // path parameter
            if (play != null && play.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(play); // http body (model) parameter
            }
            else
            {
                localVarPostBody = play; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GameByGameIdPlayPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GameView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GameView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GameView)));
            
        }

        /// <summary>
        /// Get all your and public lobbies 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;LobbyView&gt;</returns>
        public List<LobbyView> LobbiesGet ()
        {
             ApiResponse<List<LobbyView>> localVarResponse = LobbiesGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get all your and public lobbies 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;LobbyView&gt;</returns>
        public ApiResponse< List<LobbyView> > LobbiesGetWithHttpInfo ()
        {

            var localVarPath = "/lobbies";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbiesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<LobbyView>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<LobbyView>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<LobbyView>)));
            
        }

        /// <summary>
        /// Get all your and public lobbies 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;LobbyView&gt;</returns>
        public async System.Threading.Tasks.Task<List<LobbyView>> LobbiesGetAsync ()
        {
             ApiResponse<List<LobbyView>> localVarResponse = await LobbiesGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get all your and public lobbies 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;LobbyView&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<LobbyView>>> LobbiesGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/lobbies";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbiesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<LobbyView>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<LobbyView>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<LobbyView>)));
            
        }

        /// <summary>
        /// Get the state of a particular lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId"></param>
        /// <returns>LobbyView</returns>
        public LobbyView LobbyByLobbyIdGet (string lobbyId)
        {
             ApiResponse<LobbyView> localVarResponse = LobbyByLobbyIdGetWithHttpInfo(lobbyId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get the state of a particular lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId"></param>
        /// <returns>ApiResponse of LobbyView</returns>
        public ApiResponse< LobbyView > LobbyByLobbyIdGetWithHttpInfo (string lobbyId)
        {
            // verify the required parameter 'lobbyId' is set
            if (lobbyId == null)
                throw new ApiException(400, "Missing required parameter 'lobbyId' when calling GameApi->LobbyByLobbyIdGet");

            var localVarPath = "/lobby/{lobbyId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (lobbyId != null) localVarPathParams.Add("lobbyId", Configuration.ApiClient.ParameterToString(lobbyId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbyByLobbyIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LobbyView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LobbyView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LobbyView)));
            
        }

        /// <summary>
        /// Get the state of a particular lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId"></param>
        /// <returns>Task of LobbyView</returns>
        public async System.Threading.Tasks.Task<LobbyView> LobbyByLobbyIdGetAsync (string lobbyId)
        {
             ApiResponse<LobbyView> localVarResponse = await LobbyByLobbyIdGetAsyncWithHttpInfo(lobbyId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get the state of a particular lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId"></param>
        /// <returns>Task of ApiResponse (LobbyView)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LobbyView>> LobbyByLobbyIdGetAsyncWithHttpInfo (string lobbyId)
        {
            // verify the required parameter 'lobbyId' is set
            if (lobbyId == null)
                throw new ApiException(400, "Missing required parameter 'lobbyId' when calling GameApi->LobbyByLobbyIdGet");

            var localVarPath = "/lobby/{lobbyId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (lobbyId != null) localVarPathParams.Add("lobbyId", Configuration.ApiClient.ParameterToString(lobbyId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbyByLobbyIdGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LobbyView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LobbyView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LobbyView)));
            
        }

        /// <summary>
        /// Join a Lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby to join</param>
        /// <returns>LobbyView</returns>
        public LobbyView LobbyByLobbyIdJoinPost (string lobbyId)
        {
             ApiResponse<LobbyView> localVarResponse = LobbyByLobbyIdJoinPostWithHttpInfo(lobbyId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Join a Lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby to join</param>
        /// <returns>ApiResponse of LobbyView</returns>
        public ApiResponse< LobbyView > LobbyByLobbyIdJoinPostWithHttpInfo (string lobbyId)
        {
            // verify the required parameter 'lobbyId' is set
            if (lobbyId == null)
                throw new ApiException(400, "Missing required parameter 'lobbyId' when calling GameApi->LobbyByLobbyIdJoinPost");

            var localVarPath = "/lobby/{lobbyId}/join";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (lobbyId != null) localVarPathParams.Add("lobbyId", Configuration.ApiClient.ParameterToString(lobbyId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbyByLobbyIdJoinPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LobbyView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LobbyView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LobbyView)));
            
        }

        /// <summary>
        /// Join a Lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby to join</param>
        /// <returns>Task of LobbyView</returns>
        public async System.Threading.Tasks.Task<LobbyView> LobbyByLobbyIdJoinPostAsync (string lobbyId)
        {
             ApiResponse<LobbyView> localVarResponse = await LobbyByLobbyIdJoinPostAsyncWithHttpInfo(lobbyId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Join a Lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby to join</param>
        /// <returns>Task of ApiResponse (LobbyView)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LobbyView>> LobbyByLobbyIdJoinPostAsyncWithHttpInfo (string lobbyId)
        {
            // verify the required parameter 'lobbyId' is set
            if (lobbyId == null)
                throw new ApiException(400, "Missing required parameter 'lobbyId' when calling GameApi->LobbyByLobbyIdJoinPost");

            var localVarPath = "/lobby/{lobbyId}/join";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (lobbyId != null) localVarPathParams.Add("lobbyId", Configuration.ApiClient.ParameterToString(lobbyId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbyByLobbyIdJoinPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LobbyView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LobbyView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LobbyView)));
            
        }

        /// <summary>
        /// Start the game for a lobby. The lobby will be converted to a game. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby</param>
        /// <returns>GameView</returns>
        public GameView LobbyByLobbyIdStartPost (string lobbyId)
        {
             ApiResponse<GameView> localVarResponse = LobbyByLobbyIdStartPostWithHttpInfo(lobbyId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Start the game for a lobby. The lobby will be converted to a game. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby</param>
        /// <returns>ApiResponse of GameView</returns>
        public ApiResponse< GameView > LobbyByLobbyIdStartPostWithHttpInfo (string lobbyId)
        {
            // verify the required parameter 'lobbyId' is set
            if (lobbyId == null)
                throw new ApiException(400, "Missing required parameter 'lobbyId' when calling GameApi->LobbyByLobbyIdStartPost");

            var localVarPath = "/lobby/{lobbyId}/start";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (lobbyId != null) localVarPathParams.Add("lobbyId", Configuration.ApiClient.ParameterToString(lobbyId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbyByLobbyIdStartPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GameView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GameView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GameView)));
            
        }

        /// <summary>
        /// Start the game for a lobby. The lobby will be converted to a game. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby</param>
        /// <returns>Task of GameView</returns>
        public async System.Threading.Tasks.Task<GameView> LobbyByLobbyIdStartPostAsync (string lobbyId)
        {
             ApiResponse<GameView> localVarResponse = await LobbyByLobbyIdStartPostAsyncWithHttpInfo(lobbyId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Start the game for a lobby. The lobby will be converted to a game. 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="lobbyId">Id of the lobby</param>
        /// <returns>Task of ApiResponse (GameView)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<GameView>> LobbyByLobbyIdStartPostAsyncWithHttpInfo (string lobbyId)
        {
            // verify the required parameter 'lobbyId' is set
            if (lobbyId == null)
                throw new ApiException(400, "Missing required parameter 'lobbyId' when calling GameApi->LobbyByLobbyIdStartPost");

            var localVarPath = "/lobby/{lobbyId}/start";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (lobbyId != null) localVarPathParams.Add("lobbyId", Configuration.ApiClient.ParameterToString(lobbyId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbyByLobbyIdStartPost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GameView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GameView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(GameView)));
            
        }

        /// <summary>
        /// Create a new lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The name of the future game</param>
        /// <param name="isPublic">Indicates whether the lobby is visible to everyone (optional)</param>
        /// <returns>LobbyView</returns>
        public LobbyView LobbyCreateByNamePost (string name, bool? isPublic = null)
        {
             ApiResponse<LobbyView> localVarResponse = LobbyCreateByNamePostWithHttpInfo(name, isPublic);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Create a new lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The name of the future game</param>
        /// <param name="isPublic">Indicates whether the lobby is visible to everyone (optional)</param>
        /// <returns>ApiResponse of LobbyView</returns>
        public ApiResponse< LobbyView > LobbyCreateByNamePostWithHttpInfo (string name, bool? isPublic = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling GameApi->LobbyCreateByNamePost");

            var localVarPath = "/lobby/create/{name}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/json-patch+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (isPublic != null && isPublic.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(isPublic); // http body (model) parameter
            }
            else
            {
                localVarPostBody = isPublic; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbyCreateByNamePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LobbyView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LobbyView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LobbyView)));
            
        }

        /// <summary>
        /// Create a new lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The name of the future game</param>
        /// <param name="isPublic">Indicates whether the lobby is visible to everyone (optional)</param>
        /// <returns>Task of LobbyView</returns>
        public async System.Threading.Tasks.Task<LobbyView> LobbyCreateByNamePostAsync (string name, bool? isPublic = null)
        {
             ApiResponse<LobbyView> localVarResponse = await LobbyCreateByNamePostAsyncWithHttpInfo(name, isPublic);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Create a new lobby 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The name of the future game</param>
        /// <param name="isPublic">Indicates whether the lobby is visible to everyone (optional)</param>
        /// <returns>Task of ApiResponse (LobbyView)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<LobbyView>> LobbyCreateByNamePostAsyncWithHttpInfo (string name, bool? isPublic = null)
        {
            // verify the required parameter 'name' is set
            if (name == null)
                throw new ApiException(400, "Missing required parameter 'name' when calling GameApi->LobbyCreateByNamePost");

            var localVarPath = "/lobby/create/{name}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json", 
                "text/json", 
                "application/json-patch+json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (name != null) localVarPathParams.Add("name", Configuration.ApiClient.ParameterToString(name)); // path parameter
            if (isPublic != null && isPublic.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(isPublic); // http body (model) parameter
            }
            else
            {
                localVarPostBody = isPublic; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("LobbyCreateByNamePost", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<LobbyView>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (LobbyView) Configuration.ApiClient.Deserialize(localVarResponse, typeof(LobbyView)));
            
        }

        /// <summary>
        /// Return the games you participate in 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;GameView&gt;</returns>
        public List<GameView> MyGamesGet ()
        {
             ApiResponse<List<GameView>> localVarResponse = MyGamesGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Return the games you participate in 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;GameView&gt;</returns>
        public ApiResponse< List<GameView> > MyGamesGetWithHttpInfo ()
        {

            var localVarPath = "/myGames";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MyGamesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<GameView>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<GameView>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<GameView>)));
            
        }

        /// <summary>
        /// Return the games you participate in 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;GameView&gt;</returns>
        public async System.Threading.Tasks.Task<List<GameView>> MyGamesGetAsync ()
        {
             ApiResponse<List<GameView>> localVarResponse = await MyGamesGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Return the games you participate in 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;GameView&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<GameView>>> MyGamesGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/myGames";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MyGamesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<GameView>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<GameView>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<GameView>)));
            
        }

        /// <summary>
        /// Return the lobbies you&#39;ve created or joined 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;LobbyView&gt;</returns>
        public List<LobbyView> MyLobbiesGet ()
        {
             ApiResponse<List<LobbyView>> localVarResponse = MyLobbiesGetWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Return the lobbies you&#39;ve created or joined 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;LobbyView&gt;</returns>
        public ApiResponse< List<LobbyView> > MyLobbiesGetWithHttpInfo ()
        {

            var localVarPath = "/myLobbies";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MyLobbiesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<LobbyView>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<LobbyView>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<LobbyView>)));
            
        }

        /// <summary>
        /// Return the lobbies you&#39;ve created or joined 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;LobbyView&gt;</returns>
        public async System.Threading.Tasks.Task<List<LobbyView>> MyLobbiesGetAsync ()
        {
             ApiResponse<List<LobbyView>> localVarResponse = await MyLobbiesGetAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Return the lobbies you&#39;ve created or joined 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;LobbyView&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<LobbyView>>> MyLobbiesGetAsyncWithHttpInfo ()
        {

            var localVarPath = "/myLobbies";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "text/plain", 
                "application/json", 
                "text/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("MyLobbiesGet", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<LobbyView>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<LobbyView>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<LobbyView>)));
            
        }

    }
}
